import { prisma } from '@/lib/db'
import { NextRequest, NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

const explainersData = [
  {
    title: 'Iron Dome Air Defense System',
    slug: 'iron-dome-air-defense-system',
    description: "Israel's comprehensive multi-layered air defense system designed to intercept rockets, artillery shells, and mortars.",
    category: 'systems',
    difficulty: 'beginner',
    readTime: 8,
    featured: true,
    imageUrl: 'https://www.navalnews.com/wp-content/uploads/2023/08/Iron-Dome-USMC.jpg',
    whatItIs: "The Iron Dome is Israel's mobile all-weather air defense system, designed to intercept and destroy short-range rockets and artillery shells fired from distances of 4 to 70 kilometers away.",
    howItWorks: 'The system uses radar to detect incoming projectiles, calculates their trajectory, and fires interceptor missiles to neutralize threats that pose a danger to populated areas.',
    keyFeatures: ['Multi-layered Defense', 'AI Targeting', 'High Success Rate', 'Mobile Platform'],
    advantages: ['High interception rate (>90%)', 'Selective targeting', 'Quick deployment', 'Cost-effective for high-value targets'],
    disadvantages: ['High cost per interception', 'Limited against saturation attacks', 'Dependent on early warning systems'],
    realWorldUse: 'Successfully deployed in multiple conflicts, protecting Israeli cities from thousands of rocket attacks.',
    content: `# Iron Dome Air Defense System\n\nThe Iron Dome represents one of the most successful short-range air defense systems in modern military history.`,
  },
  {
    title: 'Radio Frequency Jamming Technology',
    slug: 'rf-jamming-technology',
    description: 'How RF jammers disrupt drone communications, GPS navigation, and control systems to neutralize UAV threats.',
    category: 'countermeasures',
    difficulty: 'intermediate',
    readTime: 12,
    featured: true,
    imageUrl: 'https://www.l3harris.com/sites/default/files/styles/1440_x_810/public/2023-03/58142-EW-Overview-Infographic_2880x1620-smaller.png',
    whatItIs: 'RF jamming technology disrupts radio frequency communications between drones and their operators by overwhelming the targeted frequency bands with interference signals.',
    howItWorks: 'Jammers emit powerful radio signals on the same frequencies used by drones for communication and navigation, effectively blocking or disrupting these critical links.',
    keyFeatures: ['Signal Disruption', 'Multi-frequency', 'Directional Control', 'Variable Power'],
    advantages: ['Non-kinetic neutralization', 'Reusable', 'Immediate effect', 'Scalable power levels'],
    disadvantages: ['Spectrum interference', 'Limited by line-of-sight', 'Power requirements', 'Potential collateral disruption'],
    realWorldUse: 'Widely deployed by military and security forces worldwide for drone defense at airports, government facilities, and military bases.',
    content: `# Radio Frequency Jamming Technology\n\nRF jamming represents one of the most widely deployed counter-drone technologies in use today.`,
  },
  {
    title: 'Drone Swarm Attack Tactics',
    slug: 'drone-swarm-attack-tactics',
    description: 'Understanding coordinated UAV attacks, swarm intelligence, and their implications for modern warfare.',
    category: 'threats',
    difficulty: 'advanced',
    readTime: 15,
    featured: false,
    imageUrl: 'https://deweb-519a7.b-cdn.net/post-images/6d174962-0c18-4bc8-abe6-1852765d4ed4.webp',
    whatItIs: 'Drone swarm attacks involve coordinating multiple unmanned aerial vehicles to overwhelm traditional air defense systems through sheer numbers and synchronized tactics.',
    howItWorks: 'Swarm attacks use distributed AI and communication protocols to coordinate multiple drones, allowing them to adapt in real-time, share intelligence, and execute complex multi-vector attacks.',
    keyFeatures: ['Coordinated Attack', 'AI Swarm Logic', 'Overwhelming Defense', 'Adaptive Behavior'],
    advantages: ['Overwhelms point defenses', 'Distributed resilience', 'Cost-effective scaling', 'Adaptive tactics'],
    disadvantages: ['Complex coordination required', 'Communication vulnerabilities', 'Limited individual payload', 'Regulatory restrictions'],
    realWorldUse: 'Observed in conflicts in Ukraine, Middle East, and demonstrated in military exercises worldwide.',
    content: `# Drone Swarm Attack Tactics\n\nThe emergence of drone swarm technology represents one of the most significant tactical developments in modern warfare.`,
  },
  {
    title: 'Laser Weapon Systems (LAWS)',
    slug: 'laser-weapon-systems',
    description: 'High-energy laser systems for counter-UAS applications, including power requirements and effectiveness.',
    category: 'countermeasures',
    difficulty: 'intermediate',
    readTime: 10,
    featured: false,
    imageUrl: 'https://www.lockheedmartin.com/content/dam/lockheed-martin/rms/photo/directed-energy/DE-Hero-Morphius.png',
    whatItIs: 'Laser Weapon Systems (LAWS) are directed-energy weapons that use focused light beams to disable or destroy targets.',
    howItWorks: 'High-energy lasers generate intense focused light beams that heat target materials to the point of structural failure.',
    keyFeatures: ['Directed Energy', 'Precision Targeting', 'Low Cost Per Shot', 'Silent Operation'],
    advantages: ['Near-instantaneous engagement', 'Unlimited magazine depth', 'Precise targeting', 'Minimal collateral damage'],
    disadvantages: ['High power requirements', 'Weather dependent', 'Limited range', 'Expensive initial setup'],
    realWorldUse: 'Deployed by military forces for base protection and tested on naval vessels.',
    content: `# Laser Weapon Systems (LAWS)\n\nDirected-energy weapons represent the cutting edge of counter-drone technology.`,
  },
  {
    title: 'Counter-UAS Policy Framework',
    slug: 'counter-uas-policy-framework',
    description: 'Legal and policy considerations for implementing counter-drone measures in civilian and military contexts.',
    category: 'policy',
    difficulty: 'beginner',
    readTime: 7,
    featured: false,
    imageUrl: 'https://i2.wp.com/opiniojuris.org/wp-content/uploads/scales-justice-wooden-gavel-earth-globe-d-rendering-isolated-white-background-183332238.jpg',
    whatItIs: 'The Counter-UAS Policy Framework encompasses the legal, regulatory, and operational guidelines governing the deployment and use of counter-drone technologies.',
    howItWorks: 'Policy frameworks establish clear authorities, procedures, and limitations for counter-UAS operations.',
    keyFeatures: ['Legal Framework', 'Civilian Protection', 'International Law', 'Operational Guidelines'],
    advantages: ['Clear operational authority', 'Legal protection', 'Standardized procedures', 'International coordination'],
    disadvantages: ['Complex approval processes', 'Jurisdictional challenges', 'Technology lag', 'Enforcement difficulties'],
    realWorldUse: 'Implemented by governments worldwide to regulate counter-drone operations.',
    content: `# Counter-UAS Policy Framework\n\nThe rapid proliferation of unmanned aircraft systems has created an urgent need for comprehensive policy frameworks.`,
  },
  {
    title: 'Patriot Missile Defense System',
    slug: 'patriot-missile-defense',
    description: 'Advanced surface-to-air missile system capabilities against aircraft, cruise missiles, and ballistic missiles.',
    category: 'systems',
    difficulty: 'intermediate',
    readTime: 11,
    featured: true,
    imageUrl: 'https://cloudfront-us-east-2.images.arcpublishing.com/reuters/WXJDS4WZEVN4DHF3PB7BBLIOF4.jpg',
    whatItIs: 'The Patriot is a mobile surface-to-air missile system providing area defense against aircraft, cruise missiles, and ballistic missiles.',
    howItWorks: 'The system uses phased-array radar for detection and tracking, with command-guided interceptor missiles.',
    keyFeatures: ['Long Range', 'Multi-Target', 'Mobile Platform', 'Phased Array Radar'],
    advantages: ['Proven combat effectiveness', 'Multi-threat capability', 'Mobile deployment', 'NATO interoperability'],
    disadvantages: ['High cost per intercept', 'Complex logistics', 'Large radar signature', 'Limited against maneuvering targets'],
    realWorldUse: 'Deployed by multiple NATO allies and partners, extensively used in Middle East conflicts.',
    content: `# Patriot Missile Defense System\n\nThe MIM-104 Patriot represents one of the most successful and widely deployed air defense systems.`,
  },
  // Additional explainers to reach 24
  {
    title: 'THAAD Missile Defense System',
    slug: 'thaad-missile-defense',
    description: 'Terminal High Altitude Area Defense system for intercepting ballistic missiles in their terminal phase.',
    category: 'systems',
    difficulty: 'advanced',
    readTime: 14,
    featured: false,
    imageUrl: 'https://www.lockheedmartin.com/content/dam/lockheed-martin/mfc/pc/thaad/mfc-thaad-702702-702702.jpg',
    whatItIs: 'THAAD is a transportable, ground-based missile defense system designed to shoot down short, medium, and intermediate-range ballistic missiles.',
    howItWorks: 'Uses hit-to-kill technology with no explosive warhead, relying on kinetic energy to destroy targets.',
    keyFeatures: ['Hit-to-Kill', 'High Altitude', 'Mobile Platform', 'X-Band Radar'],
    advantages: ['Extremely long range', 'High altitude intercept', 'No explosive warhead needed'],
    disadvantages: ['Very expensive', 'Complex logistics', 'Limited inventory'],
    realWorldUse: 'Deployed in South Korea, Guam, and the Middle East.',
    content: `# THAAD Missile Defense System\n\nThe Terminal High Altitude Area Defense system provides the upper-tier of a layered defense.`,
  },
  {
    title: 'GPS Spoofing Detection',
    slug: 'gps-spoofing-detection',
    description: 'Techniques for detecting and mitigating GPS spoofing attacks against drones and navigation systems.',
    category: 'countermeasures',
    difficulty: 'advanced',
    readTime: 13,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
    whatItIs: 'GPS spoofing detection systems identify when GPS signals are being manipulated to mislead drone navigation.',
    howItWorks: 'Uses multiple sensor fusion, signal analysis, and anomaly detection to identify spoofed GPS signals.',
    keyFeatures: ['Signal Analysis', 'Multi-Sensor Fusion', 'Real-time Detection', 'Alert Systems'],
    advantages: ['Prevents navigation hijacking', 'Works with existing systems', 'Can identify attack source'],
    disadvantages: ['Complex implementation', 'False positive potential', 'Requires specialized hardware'],
    realWorldUse: 'Used by military and critical infrastructure to protect against GPS manipulation attacks.',
    content: `# GPS Spoofing Detection\n\nAs drones increasingly rely on GPS for navigation, spoofing has emerged as a significant threat.`,
  },
  {
    title: 'Acoustic Drone Detection',
    slug: 'acoustic-drone-detection',
    description: 'Using sound signatures to detect and track incoming drone threats in various environments.',
    category: 'countermeasures',
    difficulty: 'beginner',
    readTime: 8,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    whatItIs: 'Acoustic detection systems use microphone arrays to identify the distinctive sound patterns of drone propellers.',
    howItWorks: 'Multiple microphones capture audio which is analyzed against known drone acoustic signatures.',
    keyFeatures: ['Passive Detection', 'No RF Emissions', 'Works in RF-Denied', 'Low Power'],
    advantages: ['Completely passive', 'Detects all drone types', 'Low cost'],
    disadvantages: ['Limited range', 'Environmental noise interference', 'Cannot identify specific model'],
    realWorldUse: 'Deployed at airports, prisons, and sensitive facilities worldwide.',
    content: `# Acoustic Drone Detection\n\nAcoustic detection offers a unique approach to identifying drone threats.`,
  },
  {
    title: 'Net Capture Systems',
    slug: 'net-capture-systems',
    description: 'Physical interception methods using nets to safely capture hostile drones intact.',
    category: 'countermeasures',
    difficulty: 'beginner',
    readTime: 6,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=800',
    whatItIs: 'Net capture systems use physical nets launched from ground platforms or interceptor drones to entangle and capture hostile UAVs.',
    howItWorks: 'Nets are deployed to ensnare drone propellers, causing them to crash safely or be captured for forensic analysis.',
    keyFeatures: ['Non-Destructive', 'Evidence Preservation', 'Safe Neutralization', 'Reusable'],
    advantages: ['Captures drone intact', 'No collateral damage', 'Preserves evidence'],
    disadvantages: ['Limited range', 'Single target engagement', 'Weather dependent'],
    realWorldUse: 'Used by law enforcement and security services for drone capture operations.',
    content: `# Net Capture Systems\n\nNet capture provides a non-destructive method for neutralizing drone threats.`,
  },
  {
    title: 'Drone Detection Radar Systems',
    slug: 'drone-detection-radar',
    description: 'Specialized radar technology optimized for detecting small, low-flying unmanned aircraft.',
    category: 'countermeasures',
    difficulty: 'intermediate',
    readTime: 11,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1569428034239-f9565e32e224?w=800',
    whatItIs: 'Counter-UAS radar systems are purpose-built to detect small drones that evade traditional air defense radar.',
    howItWorks: 'Uses specialized signal processing and waveforms optimized for small radar cross-section targets.',
    keyFeatures: ['Small Target Detection', '3D Tracking', 'Classification', 'Integration Ready'],
    advantages: ['Long detection range', 'All-weather operation', 'Tracks multiple targets'],
    disadvantages: ['Expensive', 'Can have false alarms from birds', 'Requires skilled operators'],
    realWorldUse: 'Deployed at airports, military bases, and critical infrastructure worldwide.',
    content: `# Drone Detection Radar Systems\n\nSpecialized radar plays a crucial role in counter-UAS defense.`,
  },
  {
    title: 'FPV Combat Drone Tactics',
    slug: 'fpv-combat-drone-tactics',
    description: 'First-person view drones in modern warfare: tactics, effectiveness, and countermeasures.',
    category: 'threats',
    difficulty: 'intermediate',
    readTime: 12,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800',
    whatItIs: 'FPV combat drones are small, agile UAVs piloted through a first-person video feed, used for precision strikes.',
    howItWorks: 'Operators wear goggles showing real-time video from the drone camera for precise manual control.',
    keyFeatures: ['Manual Precision', 'Low Cost', 'High Agility', 'Expendable'],
    advantages: ['Extremely low cost', 'Highly maneuverable', 'Difficult to detect'],
    disadvantages: ['Short range', 'Requires skilled pilot', 'Limited payload'],
    realWorldUse: 'Extensively used in the Ukraine conflict for anti-armor and personnel strikes.',
    content: `# FPV Combat Drone Tactics\n\nFirst-person view drones have revolutionized small-unit warfare.`,
  },
  {
    title: 'Electronic Warfare Fundamentals',
    slug: 'electronic-warfare-fundamentals',
    description: 'Core concepts of electronic warfare as applied to drone operations and counter-UAS defense.',
    category: 'countermeasures',
    difficulty: 'beginner',
    readTime: 9,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800',
    whatItIs: 'Electronic warfare encompasses the military use of the electromagnetic spectrum for attack, defense, and support.',
    howItWorks: 'EW systems detect, intercept, and disrupt enemy electronic systems while protecting friendly ones.',
    keyFeatures: ['Spectrum Dominance', 'Signal Intelligence', 'Jamming', 'Deception'],
    advantages: ['Non-kinetic effects', 'Wide area coverage', 'Reusable'],
    disadvantages: ['Complex planning required', 'Can affect friendly systems', 'Adversary adaptation'],
    realWorldUse: 'Integral component of modern military operations and counter-drone systems.',
    content: `# Electronic Warfare Fundamentals\n\nUnderstanding electronic warfare is essential for modern counter-drone operations.`,
  },
  {
    title: 'Drone Regulations Overview',
    slug: 'drone-regulations-overview',
    description: 'Key international and domestic regulations governing drone operations and airspace.',
    category: 'policy',
    difficulty: 'beginner',
    readTime: 8,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800',
    whatItIs: 'Drone regulations establish the legal framework for operating unmanned aircraft in various airspace categories.',
    howItWorks: 'Regulatory bodies set rules for drone registration, pilot certification, and operational limits.',
    keyFeatures: ['Airspace Classes', 'Registration Requirements', 'Pilot Certification', 'Operating Rules'],
    advantages: ['Safety standards', 'Accountability', 'Integration framework'],
    disadvantages: ['Compliance burden', 'Slow adaptation', 'Jurisdictional complexity'],
    realWorldUse: 'FAA, EASA, and national aviation authorities worldwide enforce drone regulations.',
    content: `# Drone Regulations Overview\n\nUnderstanding drone regulations is essential for both operators and security professionals.`,
  },
  {
    title: 'Directed Energy Weapons Overview',
    slug: 'directed-energy-weapons-overview',
    description: 'Comprehensive look at directed energy technologies including lasers, microwaves, and particle beams.',
    category: 'countermeasures',
    difficulty: 'advanced',
    readTime: 14,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800',
    whatItIs: 'Directed energy weapons transmit focused energy to damage or disable targets without conventional projectiles.',
    howItWorks: 'Different DEW types use various forms of energy including photons, microwaves, or charged particles.',
    keyFeatures: ['Speed of Light', 'Precision', 'Deep Magazine', 'Scalable Effects'],
    advantages: ['Near-instant engagement', 'Low cost per shot', 'Graduated response'],
    disadvantages: ['Power hungry', 'Weather limitations', 'Range limits'],
    realWorldUse: 'Fielded by US military and allies for counter-drone and missile defense.',
    content: `# Directed Energy Weapons Overview\n\nDirected energy represents a transformational military technology.`,
  },
  {
    title: 'Counter-Drone Market Analysis',
    slug: 'counter-drone-market-analysis',
    description: 'Overview of the global counter-UAS market, key players, and technology trends.',
    category: 'policy',
    difficulty: 'intermediate',
    readTime: 10,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
    whatItIs: 'Analysis of the multi-billion dollar counter-drone industry and its projected growth.',
    howItWorks: 'Market dynamics driven by threat evolution, regulatory changes, and technology advancement.',
    keyFeatures: ['Market Size', 'Key Players', 'Growth Trends', 'Regional Analysis'],
    advantages: ['Investment guidance', 'Technology roadmap', 'Competitive intelligence'],
    disadvantages: ['Rapidly changing', 'Classified segments hidden', 'Regional variations'],
    realWorldUse: 'Used by defense planners, investors, and industry strategists.',
    content: `# Counter-Drone Market Analysis\n\nThe counter-drone market is experiencing rapid growth.`,
  },
  {
    title: 'Kinetic Interceptor Systems',
    slug: 'kinetic-interceptor-systems',
    description: 'Physical projectile-based systems for destroying drones including missiles, guns, and interceptors.',
    category: 'countermeasures',
    difficulty: 'intermediate',
    readTime: 11,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800',
    whatItIs: 'Kinetic interceptors physically destroy drone targets using projectiles, missiles, or collision.',
    howItWorks: 'Systems track targets and guide interceptors or projectiles to physically destroy the threat.',
    keyFeatures: ['Physical Destruction', 'High Confidence', 'All-Weather', 'Proven Technology'],
    advantages: ['Guaranteed destruction', 'Works against all drone types', 'Established supply chains'],
    disadvantages: ['Ammunition costs', 'Collateral damage risk', 'Debris concerns'],
    realWorldUse: 'Military forces worldwide use kinetic systems for high-value asset protection.',
    content: `# Kinetic Interceptor Systems\n\nKinetic intercept remains a reliable method for drone neutralization.`,
  },
  {
    title: 'Autonomous Drone Operations',
    slug: 'autonomous-drone-operations',
    description: 'Understanding fully autonomous drone capabilities and the challenges they pose for defense.',
    category: 'threats',
    difficulty: 'advanced',
    readTime: 13,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1508614999368-9260051292e5?w=800',
    whatItIs: 'Autonomous drones operate with varying levels of independence from human operators.',
    howItWorks: 'AI and machine learning enable drones to navigate, identify targets, and make decisions independently.',
    keyFeatures: ['AI Decision Making', 'GPS-Denied Navigation', 'Target Recognition', 'Mission Planning'],
    advantages: ['No operator link to jam', 'Complex mission capability', 'Reduced latency'],
    disadvantages: ['Ethical concerns', 'Unpredictable behavior', 'Technical complexity'],
    realWorldUse: 'Increasingly used by militaries for reconnaissance and strike missions.',
    content: `# Autonomous Drone Operations\n\nAutonomous capabilities represent the next frontier in drone warfare.`,
  },
  {
    title: 'Critical Infrastructure Protection',
    slug: 'critical-infrastructure-protection',
    description: 'Strategies and systems for protecting power plants, airports, and other vital facilities from drone threats.',
    category: 'policy',
    difficulty: 'intermediate',
    readTime: 10,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800',
    whatItIs: 'Comprehensive approach to defending critical infrastructure from unmanned aircraft threats.',
    howItWorks: 'Layered defense combining detection, tracking, identification, and neutralization systems.',
    keyFeatures: ['Layered Defense', 'Sensor Fusion', 'Rapid Response', 'Integration'],
    advantages: ['Comprehensive protection', 'Multiple fail-safes', 'Scalable'],
    disadvantages: ['High cost', 'Complex integration', 'False alarm management'],
    realWorldUse: 'Deployed at airports, power plants, government facilities globally.',
    content: `# Critical Infrastructure Protection\n\nProtecting critical infrastructure from drone threats is a national security priority.`,
  },
  {
    title: 'Drone Forensics and Attribution',
    slug: 'drone-forensics-attribution',
    description: 'Techniques for analyzing captured drones and attributing attacks to their sources.',
    category: 'policy',
    difficulty: 'advanced',
    readTime: 12,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800',
    whatItIs: 'Forensic analysis of captured or downed drones to identify origin, modifications, and operators.',
    howItWorks: 'Combines hardware analysis, software examination, and intelligence to attribute attacks.',
    keyFeatures: ['Hardware Analysis', 'Software Extraction', 'Supply Chain Tracking', 'Intelligence Fusion'],
    advantages: ['Evidence for prosecution', 'Adversary understanding', 'Deterrence'],
    disadvantages: ['Time intensive', 'Requires intact samples', 'Technical expertise needed'],
    realWorldUse: 'Used by military and law enforcement for post-incident investigation.',
    content: `# Drone Forensics and Attribution\n\nForensic analysis is crucial for understanding and deterring drone attacks.`,
  },
  {
    title: 'Multi-Domain Counter-UAS',
    slug: 'multi-domain-counter-uas',
    description: 'Integrated defense approaches spanning land, air, sea, space, and cyber domains.',
    category: 'systems',
    difficulty: 'advanced',
    readTime: 15,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
    whatItIs: 'Multi-domain counter-UAS integrates capabilities across all warfare domains for comprehensive defense.',
    howItWorks: 'Sensor networks, command systems, and effectors across domains work together seamlessly.',
    keyFeatures: ['Domain Integration', 'Shared Awareness', 'Coordinated Effects', 'Resilience'],
    advantages: ['No single point of failure', 'Comprehensive coverage', 'Synergistic effects'],
    disadvantages: ['Extremely complex', 'Interoperability challenges', 'High cost'],
    realWorldUse: 'Modern military doctrine emphasizes multi-domain approaches.',
    content: `# Multi-Domain Counter-UAS\n\nModern threats require multi-domain approaches to counter-drone defense.`,
  },
  {
    title: 'Low-Cost Drone Threats',
    slug: 'low-cost-drone-threats',
    description: 'Understanding the challenge posed by inexpensive commercial drones weaponized for attacks.',
    category: 'threats',
    difficulty: 'beginner',
    readTime: 7,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1579829366248-204fe8413f31?w=800',
    whatItIs: 'Commercial off-the-shelf drones modified for hostile purposes represent a growing security challenge.',
    howItWorks: 'Inexpensive consumer drones can be easily modified to carry explosives or conduct surveillance.',
    keyFeatures: ['Low Cost', 'Easy Availability', 'Modification Potential', 'Mass Employment'],
    advantages: ['Asymmetric advantage', 'Difficult to defend economically', 'Plausible deniability'],
    disadvantages: ['Limited capability', 'Short range', 'Weather sensitive'],
    realWorldUse: 'Used by non-state actors, terrorists, and criminals worldwide.',
    content: `# Low-Cost Drone Threats\n\nThe proliferation of cheap drones has democratized aerial threats.`,
  },
  {
    title: 'Counter-UAS Training Programs',
    slug: 'counter-uas-training-programs',
    description: 'Overview of training requirements and programs for counter-drone operators and planners.',
    category: 'policy',
    difficulty: 'beginner',
    readTime: 8,
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800',
    whatItIs: 'Specialized training programs prepare personnel to operate counter-drone systems effectively.',
    howItWorks: 'Combines classroom instruction, simulation, and live exercises for comprehensive preparation.',
    keyFeatures: ['Operator Training', 'Tactical Planning', 'System Integration', 'Exercise Programs'],
    advantages: ['Improved readiness', 'Reduced errors', 'Standardization'],
    disadvantages: ['Resource intensive', 'Rapidly evolving curriculum', 'Equipment requirements'],
    realWorldUse: 'Military, law enforcement, and security organizations conduct specialized training.',
    content: `# Counter-UAS Training Programs\n\nEffective counter-drone operations require well-trained personnel.`,
  },
]

export async function GET(request: NextRequest) {
  const authHeader = request.headers.get('authorization')
  const expectedToken = `Bearer ${process.env.CRON_SECRET}`

  if (authHeader !== expectedToken) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Get current count
  const currentCount = await prisma.explainer.count()

  return NextResponse.json({
    message: 'Explainer seed endpoint ready',
    currentExplainers: currentCount,
    explainersToSeed: explainersData.length,
  })
}

export async function POST(request: NextRequest) {
  const authHeader = request.headers.get('authorization')
  const expectedToken = `Bearer ${process.env.CRON_SECRET}`

  if (authHeader !== expectedToken) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const results = {
    created: [] as string[],
    skipped: [] as string[],
    errors: [] as string[],
  }

  for (const explainer of explainersData) {
    try {
      const existing = await prisma.explainer.findUnique({
        where: { slug: explainer.slug },
      })

      if (existing) {
        results.skipped.push(explainer.title)
        continue
      }

      await prisma.explainer.create({
        data: explainer,
      })
      results.created.push(explainer.title)
    } catch (error) {
      results.errors.push(`${explainer.title}: ${error instanceof Error ? error.message : 'Unknown error'}`)
    }
  }

  const finalCount = await prisma.explainer.count()

  return NextResponse.json({
    success: true,
    results,
    totalExplainers: finalCount,
  })
}
